### ISSUE TITLE
App stuck on loading screen.

### ISSUE THREAD

**Issue by d4r4ki4n** [revzim/ttv-viewer#2]
App is just hanging forever on loading screen. I can access the localhost server and manually input a channel name to view it in my browser and it's clearly working, but I can't login that way.

**Comment by ghost** [comment]
I think my issue is this as well? I just installed the app and it never move past Loading ttv-viewer.

**Comment by revzim** [comment]
Apologies, I haven't looked at this project in about a month, but I was able to identify the problem and updated with a fix. 

The issue should be fixed with the new build.
If there are any other issues, feel free to open a new issue. Please provide information about your pc specs and any other helpful identifiable information to make the debugging process easier. Thank you.
[0.0.22 release](https://github.com/revzim/ttv-viewer/releases/tag/0.0.22)
