### ISSUE TITLE
Getting purple screen at the beginning of the stream

### ISSUE THREAD

**Issue by RoyRiv3r** [revzim/ttv-viewer#3]
Seems like even this app is not avoiding ads Sadge
![PMPgoJD](https://user-images.githubusercontent.com/41067116/102773730-0302e000-438a-11eb-9b26-d50b282bd308.png)

Channel was Bob Ross.
I'll keep watching if there is midroll ads or so

**Comment by revzim** [comment]
Thanks for bringing this to my attention.

According to a few other individuals within the community, this seems to be occurring anywhere the embedded player is being utilized to signify that an ad is shown cross-site/platform (which I'm sure you could tell).  

Unfortunately, I have no fix as of right now; however, for the time being, thank you for testing/using this application. I will continue to monitor this issue (purple warning screen) and I'll update the app as soon as a fix is found.

**Comment by revzim** [comment]
@N3ars Have you been seeing the purple screen lately?  

I haven't seen the purple screen message since I pushed the new release yesterday and would like to know if others have still been experiencing the purple screen/pre-rolls.

**Comment by RoyRiv3r** [comment]
Hello @revzim I'm currently watching stream, didn't get any purple screen or ads since last time. If there are any, i'll give feedback here.

I was wondering if i can suggest some modifications for the app, if possible, should i put them here or start a new topic. 

Thanks for your amazing work.

**Comment by RoyRiv3r** [comment]
Well I spoke too fast I just did get a purple screen on Lirik stream [
![UT3yd5F](https://user-images.githubusercontent.com/41067116/102918816-f19ffd80-4487-11eb-9096-1fa57e3d6e71.png)
](url)

**Comment by revzim** [comment]
> 
> 
> Hello @revzim I'm currently watching stream, didn't get any purple screen or ads since last time. If there are any, i'll give feedback here.
> 
> I was wondering if i can suggest some modifications for the app, if possible, should i put them here or start a new topic.
> 
> Thanks for your amazing work.

@N3ars No problem and glad I could make something someone else could enjoy, as well.  

And yes, of course. Any time you want to suggest anything, feel free.  I've made a [SUGGESTIONS](https://github.com/revzim/ttv-viewer/issues/5) 'issue.' Post any and all suggestions in there and I'll make sure to check them out. 

As for the purple screen, I'll make sure to add his stream to the streams to test with.  I've been messing around with the pre-flight requests, modifying some of the payload params. I'll make sure to update this thread if I find anything worth while, but it will most likely take some time due to the feeling of 'psuedo-randomness' with these purple message screens.

**Comment by revzim** [comment]
As of right now, I believe I've found the fix to the purple screen message and I've pushed a new release [ttv-viewer 0.0.23](). 

I'm going to close this issue for now, but will reopen if I am wrong about this fix.

**Comment by RoyRiv3r** [comment]
I think like some people said, they pushed the purple screen from server side so modifying the post request doesn't do much, i think also ads and purple screen are two different things, i saw people complaining about ads in the chat while i'm not getting any purple screen or ads maybe i'm wrong.
Finally i've seen the twitch mod apk and there are no purple screen or ads, maybe we should look into that how it works and simulate it like that app but my knowledge is very limited in this domain. 
Thanks for your time and effort. 


Edit : Last thing i figure this out, the purple screen doesn't work for every stream channel some of them have it some don't

**Comment by revzim** [comment]
> I think like some people said, they pushed the purple screen from server side so modifying the post request doesn't do much, 

Yes and no.

The technology used is called SSAI (Server Side Ad Insertion). I am in no means an expert in the tech and I mean no offense by this, but whoever has told you/wherever you read that modifying requests to the server doesn't do much, isn't/wasn't very knowledgeable about the subject; however, it does make distinction and execution of blocking 'more difficult' because SSAI is a newer technology that not many have experience with as well as added security features, etc.
  * If you've any interest in this, [Amazon's article on SSAI](https://aws.amazon.com/media/tech/what-server-side-ad-insertion-ssai/) that has examples of the workflow as well as a decent article to get a better understanding about how the technology works.

> i think also ads and purple screen are two different things, i saw people complaining about ads in the chat while i'm not getting any purple screen or ads maybe i'm wrong.

I believe you are correct in speculating that ads and the purple screen are two different things.  So far, everything about what the purple screen is or isn't is pure speculation, so take this with a grain of salt.  

However, I remember when twitch first rolled out SSAI (between a month and two months ago, and feel free to correct me if I'm wrong) and ublock wasn't catching any ads anymore, there also was a 'purple message type screen' that would play multiple times even when ads weren't playing just to annoy the viewer that was blocking ads. This makes me believe that the assumption that ads != purple message screen is correct.

> Finally i've seen the twitch mod apk and there are no purple screen or ads, maybe we should look into that how it works and simulate it like that app but my knowledge is very limited in this domain.

To be honest, I also don't have very much experience with apks, so that might not be the best avenue, but nonetheless, it's interesting that even ads aren't playing.
Most (if not all) companies roll-out updates in 'waves.' This makes diagnosing and debugging exact scenarios difficult (especially in the early stages) until the behavior of the new implementation (purple message screen) is consistent.  And right now, that's the exact problem, the behavior of the purple message screen is very inconsistent.

**Comment by RoyRiv3r** [comment]
I see ! i didn't know that, I guess now we have to discover how it works and find a solution, thanks for clarifying everything,

**Comment by revzim** [comment]
Yeah exactly and no problem, glad I could help.  If I do some more debugging later tonight and have any updates, I'll post them here.

**Comment by RoyRiv3r** [comment]
I tried to switch the user agent to `Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-G973N Build/PPR1.190810.011) tv.twitch.android.app/9.10.0/910000` on my browser and i kept the addon TTV ad-block, i get the android interface but no ads and no purple screen appeared, maybe there is a path to exploit

**Comment by revzim** [comment]
> 
> 
> I tried to switch the user agent to `Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-G973N Build/PPR1.190810.011) tv.twitch.android.app/9.10.0/910000` on my browser and i kept the addon TTV ad-block, i get the android interface but no ads and no purple screen appeared, maybe there is a path to exploit

Very cool find and thanks for letting me know!  Later on I'll implement this and do a little testing. As long as you don't report back seeing any purple message screen/pre-rolls/mid-rolls in the meantime, this could be a very easy fix.

Edit: 
I just got a purple screen while testing.  I want to clean up this issue thread a little, so I'm going to be closing and re-opening a generic 'purple message screen' issue to start a new fresh thread.
